project_id = "phvlbmszlhdlgwvxuxwk"

[functions.msg91-send-otp]
verify_jwt = false

[functions.msg91-verify-otp]
verify_jwt = false

[functions.rc-verification]
verify_jwt = true

[functions.rc-webhook]
verify_jwt = false

[functions.fastag-verification]
verify_jwt = true

[functions.challans-verification]
verify_jwt = true

# Keep existing functions working with defaults
[functions.cashfree-create-order]
# Uses default verify_jwt (true). Change to false if you call it publicly from client.

[functions.cashfree-verify-order]
# Uses default verify_jwt (true). Change to false if you call it publicly from client.

[functions.vehicle-info]
verify_jwt = true
