// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phvlbmszlhdlgwvxuxwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBodmxibXN6bGhkbGd3dnh1eHdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTk4NjMsImV4cCI6MjA3MTc3NTg2M30._6TNxwMYoLqAx4jqKGqLjzuZHQEWVIAGMiLSTFLJCRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});