// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dffjovobqzrdfwmpkhzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmZmpvdm9icXpyZGZ3bXBraHpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjQ3NDUsImV4cCI6MjA2OTU0MDc0NX0.bc5dFkEhWZC6zIJ-yFl5429jFc7dLnlRGQa8RtDQnPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});